### ISSUE TITLE
Clients receive duplicate emails

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-cloudserver#183]
From @nzola 

> When one email is sent to multiple Lokole clients), each client receives duplicate emails of the number of the total clients. eg. I have 3 Lokole clients. When I send one email from Internet to all the 3 clients, they all receive each 3 emails instead of one each and yet the 3 clients are each in different Lokole boxes or networks (nzola20, nzola21 and nzola23). This does not make any difference I put some clients in TO, CC or BCC.

**Comment by c-w** [comment]
If an email is sent to 3 Lokoles from the internet, we'll receive three distinct emails in the server for that since each of the Lokoles acts like an entirely distinct mailbox, e.g. imagine sending an email to Outlook and GMail: both providers will have to receive a copy of the email.

The only I way I see to fix this is to make the processing of the emails idempotent based on the email content instead of treating each email as a separate new event (see patch below).

```patch
diff --git a/opwen_email_server/actions.py b/opwen_email_server/actions.py
index e6e8d67..02acb4c 100644
--- a/opwen_email_server/actions.py
+++ b/opwen_email_server/actions.py
@@ -1,4 +1,5 @@
 from abc import ABC
+from hashlib import sha256
 from typing import Callable
 from typing import Iterable
 from typing import Tuple
@@ -150,13 +151,11 @@ class ReceiveInboundEmail(_Action):
     def __init__(self,
                  auth: AzureAuth,
                  raw_email_storage: AzureTextStorage,
-                 next_task: Callable[[str], None],
-                 email_id_source: Callable[[], str] = None):
+                 next_task: Callable[[str], None]):
 
         self._auth = auth
         self._raw_email_storage = raw_email_storage
         self._next_task = next_task
-        self._email_id_source = email_id_source or self._new_email_id
 
     def _action(self, client_id, email):  # type: ignore
         domain = self._auth.domain_for(client_id)
@@ -164,7 +163,7 @@ class ReceiveInboundEmail(_Action):
             self.log_event(events.UNREGISTERED_CLIENT, {'client_id': client_id})  # noqa: E501
             return 'client is not registered', 403
 
-        email_id = self._email_id_source()
+        email_id = self._new_email_id(email)
 
         self._raw_email_storage.store_text(email_id, email)
 
@@ -174,8 +173,8 @@ class ReceiveInboundEmail(_Action):
         return 'received', 200
 
     @classmethod
-    def _new_email_id(cls) -> str:
-        return str(uuid4())
+    def _new_email_id(cls, email: str) -> str:
+        return sha256(email.encode('utf-8')).hexdigest()
 
 
 class DownloadClientEmails(_Action):
```

**Comment by nzola** [comment]
admin@nzola40.lokole.ca,
admin@nzola42.lokole.ca,
admin@nzola43.lokole.ca,
admin@nzola44.lokole.ca,
nzola@nzola40.lokole.ca,
nzola@nzola42.lokole.ca,
nzola@nzola44.lokole.ca,
admin@nzola46.lokole.ca,
nzola@nzola46.lokole.ca,
nzola@nzola43.lokole.ca,
nzola@nzola45.lokole.ca,
nzola@nzola47.lokole.ca,
admin@nzola45.lokole.ca,
admin@nzola47.lokole.ca, nzolantima@nzola40.lokole.ca

**Comment by c-w** [comment]
@nzola What's that comment about?
