### ISSUE TITLE
Add indicator for number of emails to be synced

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-cloudserver#185]
See https://github.com/ascoderu/opwen-webapp/issues/170

**Comment by c-w** [comment]
@nzola I've implemented the "how many emails will be delivered to the Lokole at the next sync" metric on the cloud server.

The change is not yet deployed but I'll work on getting a deployment out in the next few days and update you when it's done.

Once the new feature is deployed, you'll be able to check the number of pending emails for a given Lokole by executing this on the terminal:

```sh
curl -u '{ENTER_USER}:{ENTER_PASSWORD}' https://mailserver.lokole.ca/api/email/metrics/pending/{ENTER_LOKOLE_NAME}.lokole.ca
```

In the future we may also implement a dashboard, but for now I don't believe that's the highest priority.

**Comment by nzola** [comment]
Thanks for the insights. This would be a great future to have to watch out
mail transactions especially during the pilot project.

**Comment by c-w** [comment]
@nzola This functionality has now been deployed.
