### ISSUE TITLE
Add encryption

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-cloudserver#20]
The data sent from/to the Lokole clients should be encrypted using a cypher that doesn't increase file size (e.g. AES) so that the contents of the email packages that get exchanged can't be viewed by other parties. Once the data is in Azure or on the device, it can safely be decrypted. The `client_id` or something related to the `clients_auth` table might make a good encryption key since both the client and server are aware of it and it prevents having a single shared encryption key across all clients.

The data will have to be encrypted before the server returns it to the client, in [client_read.py](https://github.com/ascoderu/opwen-cloudserver/blob/1ba4e1707fb6669555d3a086bd6bf3476ed55db6/opwen_email_server/api/client_read.py#L19). The data will also have to be encrypted before the client sends it to the server, in [sync.py](https://github.com/ascoderu/opwen-webapp/blob/687b4d971aa2f2484ddd62c1a35b35062a8c55aa/opwen_email_client/domain/email/sync.py#L72).

The data will have to be decrypted before the server tries to parse the emails, in [store_written_client_emails.py](https://github.com/ascoderu/opwen-cloudserver/blob/a1104e1edaf70d5c4c91c3ef1dfd5567fa4fdc08/opwen_email_server/api/store_written_client_emails.py#L14). The data will also have to be decypted before the client adds the emails to its local database, in [sync.py](https://github.com/ascoderu/opwen-webapp/blob/687b4d971aa2f2484ddd62c1a35b35062a8c55aa/opwen_email_client/domain/email/sync.py#L62).

**Comment by c-w** [comment]
Looks like a useful abstraction: https://github.com/nils-werner/zget/blob/a22afaabd0d73d7905a1eaa37591e436fe844ff9/zget/crypto.py

**Comment by c-w** [comment]
Seems hard to find good streaming encryption libraries, so I wonder if encrypting each JSONL entry on its own would also work.

**Comment by c-w** [comment]
> Seems hard to find good streaming encryption libraries, so I wonder if encrypting each JSONL entry on its own would also work.

This will likely not work since it'll randomize the bytes before encryption and therefore increase our bandwidth usage.

**Comment by c-w** [comment]
@NjengaSaruni Un-assigning as it's been a while since I've heard from you. Please reach out if you're still interested and available in the task. Thanks in advance!

**Comment by adamsclafani** [comment]
Slight update of the task for personal reference :)

On the server side, the data must be encrypted in [actions.py](https://github.com/ascoderu/opwen-cloudserver/blob/3453a136fe7a1523c48af95d5a1902e64563b37d/opwen_email_server/actions.py#L182) (returning email to client).
The data must be decrypted in [actions.py](https://github.com/ascoderu/opwen-cloudserver/blob/3453a136fe7a1523c48af95d5a1902e64563b37d/opwen_email_server/actions.py#L108) (parsing email written by client)

On the client side, the data must be encrypted in [sync.py](https://github.com/ascoderu/opwen-webapp/blob/2105b47a8b5ad175006068203d46f93f81ef5e1c/opwen_email_client/domain/email/sync.py#L97) while uploading 
The data must be decrypted in [sync.py](https://github.com/ascoderu/opwen-webapp/blob/2105b47a8b5ad175006068203d46f93f81ef5e1c/opwen_email_client/domain/email/sync.py#L86) while downloading

**Comment by adamsclafani** [comment]
In order to make this as smooth as possible, this is my strategy at the moment:

## Steps:
1. Utilize [this](https://github.com/nils-werner/zget/blob/a22afaabd0d73d7905a1eaa37591e436fe844ff9/zget/crypto.py) and port it to an api that conforms to our style. 
*This code uses stuff from the "hazardous material layer" from the cryptography package so the port will contain very little (if any) modification to the encryption/decryption logic assuming the logic is correct 
2. Test such api
3. Add/integrate it to the server
4. Add/integrate it to the web app

**Comment by c-w** [comment]
Sounds like a good plan @adamsclafani.

It would be ideal if you could add the integration code first to [compression-benchmarks](https://github.com/ascoderu/compression-benchmarks) so that we can verify the encrypt/decrypt code in isolation and verify that the size overhead is low-to-zero as expected.

Some code pointers for that project:

- [Here](https://github.com/ascoderu/compression-benchmarks/blob/9145beccd4179975766e2c5c1de9ff3d965db3b7/benchmarks/__main__.py#L62) is where we're setting up all the test-cases. I'd suggest to add a new concept of an "encryptor" for which we can have two implementations at the start: no encryption and AES-stream. The interface for this concept can be something like this:

```py
class _Encryption(ABC):
    @property
    def extension(self) -> str: pass

    def encrypt(self, fobj: IO[bytes]) -> IO[bytes]: pass

    def deserialize(self, fobj: IO[bytes]) -> IO[bytes]: pass
```

- [Here](https://github.com/ascoderu/compression-benchmarks/blob/9145beccd4179975766e2c5c1de9ff3d965db3b7/benchmarks/__main__.py#L71-L72) is the main loop which takes an email, serializes it and writes it to a compression stream. We can wrap the serialization stream with the encryption stream and should be good to go.

There are several benefits to this approach:

1. The initial implementation of the encryption logic is entirely decoupled from the rest of the Lokole system so it should be somewhat simpler to implement.

2. We get testing almost for free since the compression-benchmarks project already includes some [invariant testing](https://github.com/ascoderu/compression-benchmarks/blob/9145beccd4179975766e2c5c1de9ff3d965db3b7/benchmarks/tests.py) that should be easily adaptable for the compressor concept.

3. We get performance benchmarking for free and so can easily see how adding the encryption will affect the runtime of the system.

**Comment by adamsclafani** [comment]
See [this](https://github.com/ascoderu/compression-benchmarks/pull/1)

**Comment by c-w** [comment]
Thanks to @adamsclafani's great work in https://github.com/ascoderu/compression-benchmarks/pull/1, we now have a way forward for implementing encryption. As a next step, we should integrate encryption into [xtarfile](https://github.com/ascoderu/xtarfile) so that the client and server can both leverage it.

**Comment by KanishkT123** [comment]
Hey @c-w 

@Smarker and I want to try to resolve this issue, but we have a question. What do you mean by integrating encryption into xtarfile? Since that's a compression library, does it really need to have encryption/decryption capabilities, or are we misunderstanding?

**Comment by c-w** [comment]
@KanishkT123 @Smarker Thanks so much for reaching out and for offering to help out.

I was thinking to add the encryption capabilities to [xtarfile](https://github.com/ascoderu/xtarfile) mostly for convenience: both pieces of the Lokole infrastructure ([server](https://github.com/ascoderu/opwen-cloudserver), [client](https://github.com/ascoderu/opwen-webapp)) already depend on xtarfile, so adding encryption in that library will enable us to transparently add encryption to the system: essentially just update the flags passed to xtarfile without any further code changes required. This reduces technical risk for the feature roll-out.

Additionally, having encryption as part of multi-file compression is not uncommon, e.g. the zip format supports this (e.g. see the `pwd` argument in [ZipFile.open](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.open)), so I don't believe it'll be terrible design to push the encryption into xtarfile.

Thoughts?

**Comment by KanishkT123** [comment]
Upon further research, it does seem like it's actually standard to have some encryption capabilities within compression libraries. 7Zip, ZipFile, etc all seem to have at least some non-trivial encryption support, so I do think this is totally fine.

If I understand correctly, you'd like to essentially allow xtarfile to one-shot encrypt and compress similar to what ZipFile is doing, but with the zstd format? In that case, is there a specific kind of encryption library you have in mind for us to use?

**Comment by Smarker** [comment]
I think we'd want to use the AES encryption that adam implemented in [his compression benchmarks PR](https://github.com/ascoderu/compression-benchmarks/pull/1/files), since we have performance metrics on that.

**Comment by c-w** [comment]
Correct, this task is about porting Adam's code from the [AesEncryption](https://github.com/ascoderu/compression-benchmarks/blob/6f159cdf38ab8df2a0a0d0bfc59359693ac3eb34/benchmarks/encryption.py#L242) in the benchmarks project to xtarfile and to make the encryption option configurable, e.g. something like this (adapting the example from xtarfile's readme, actual interface design is up to you):

```py
import xtarfile as tarfile

with tarfile.open('some-archive', 'w:zstd', encryption='aes', aes_key='supersecret') as archive:
    archive.add('a-file.txt')

with tarfile.open('some-archive', 'r:zstd', encryption='aes', aes_key='supersecret') as archive:
    archive.extractall()
```

**Comment by Smarker** [comment]
I may come back to this a bit later. Something came up so it will be a bit hard for me to work on this for a while, so I wanted to give a heads up, in case anyone else wanted to also pick this up.
