### ISSUE TITLE
Backup secrets to Azure Blob Storage

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-cloudserver#22]
After the setup of a new system is done, the [setup.sh](https://github.com/ascoderu/opwen-cloudserver/blob/1ba4e1707fb6669555d3a086bd6bf3476ed55db6/docker/setup/setup.sh) script should upload the secrets to a container in Azure Blob Storage so that they don't only live on one developer's machine.

This can easily be achieved by first creating a new "secrets" container via the [az storage container create](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest) command and then populating the container via the [az storage blob upload-batch](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-upload-batch) command to upload all the files from a local directory to a container.

**Comment by laura-barluzzi** [comment]
Is there a preferred name for the container? Is it `backup-secrets` good or I should just call name it `secrets`? Also, is it ok to add the lines for the job just after we create the files in `/secrets` [here](https://github.com/ascoderu/opwen-cloudserver/blob/1ba4e1707fb6669555d3a086bd6bf3476ed55db6/docker/setup/setup.sh#L90)?
