### ISSUE TITLE
Improve serialization format

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-cloudserver#25]
The data sent from/to the Lokole clients is currently serialized as JSON. We should investigate alternatives like msgpack, avro, protocol buffers, bson, etc. to see if they reduce the size of the serialized emails.

This task is related to https://github.com/ascoderu/opwen-cloudserver/issues/5 in that the serialization format chosen should play well with compression. We're optimizing for the minimum total number of bytes sent over the wire across compression format plus serialization format. It's not a requirement to keep a human readable encoding for the transfer protocol, but it is a requirement that the data sent over the wire can be unpacked in a streaming fashion into Python dictionaries. I can provide some test files for running of benchmarks.

The data will have to be serialized before the server returns it to the client, in [client_read.py](https://github.com/ascoderu/opwen-cloudserver/blob/1ba4e1707fb6669555d3a086bd6bf3476ed55db6/opwen_email_server/api/client_read.py#L19). The data will also have to be serialized before the client sends it to the server, in [sync.py](https://github.com/ascoderu/opwen-webapp/blob/687b4d971aa2f2484ddd62c1a35b35062a8c55aa/opwen_email_client/domain/email/sync.py#L72).

The data will have to be deserialized before the server tries to parse the emails, in [store_written_client_emails.py](https://github.com/ascoderu/opwen-cloudserver/blob/a1104e1edaf70d5c4c91c3ef1dfd5567fa4fdc08/opwen_email_server/api/store_written_client_emails.py#L14). The data will also have to be deserialized before the client adds the emails to its local database, in [sync.py](https://github.com/ascoderu/opwen-webapp/blob/687b4d971aa2f2484ddd62c1a35b35062a8c55aa/opwen_email_client/domain/email/sync.py#L62).

**Comment by cicorias** [comment]
Isn’t gzip compression being used? Or is this using smtp and not http?

**Comment by c-w** [comment]
We're currently using JSONL serialization with gzip compression to exchange emails via HTTP between the clients and services.

We suspect that it's possible to save quite a bit of bandwidth by switching to a less redundant serialization format (e.g. msgpack) since currently we re-include the full object metadata for every email.

Additionally, if the serialization format natively supports a binary type, this will likely lead to another bandwidth saving since currently we use base64 encoding for binary data like attachments and inline images.

**Comment by c-w** [comment]
Moved benchmarks to main Ascoderu organization: https://github.com/ascoderu/compression-benchmarks

**Comment by c-w** [comment]
According to the benchmarks, serialization format has a negligible impact on transfer size. Resolving this issue since JSONL is good enough.
