### ISSUE TITLE
Forms in email

### ISSUE THREAD

**Issue by aidan-fitz** [ascoderu/opwen-cloudserver#348]
Users should be able to embed forms in their emails. The form method would be `EMAIL`, and clicking the submit button would send a response back to the sender.

Example form:
```html
<form method="EMAIL">
  What is your name?
  <input type="text" name="name">

  <input type="submit" value="Submit">
</form>
```

We could use this feature to solicit feedback on the Lokole product. (The issue is, it won't work on local-only installations, such as the IIAB edition.)

I've proposed that IIAB add LimeSurvey to their software collection; users of the IIAB edition can use that instead. See iiab/iiab#1355.

**Comment by c-w** [comment]
Closing this since we no longer have a user use-case for this.
